var myArray = [
  "$(function(){\n\t$.database.get('Password')\n});",
  "exec({\n\t'Password' : 'KbJ7zpQ',\n\t'Username' : 'Administrator'\n});",
  ">>> Command Returned 2",
  ">>> Return 0;",
  "## Server Connected",
  "## Server Disconnected",
  "## Connection Refused",
  "ACCESS DENIED",
  "ACCESS GRANTED",
  "Password: ********\n>>> Incorrect Password\n## Server Disconnected",
  "\n\nNMAP\n\n\tIP: 198.162.0.24\n\tPlatform: Linux armv7\n\tUsers Connected: 27\n\tNetmask: 255.255.255.0\n\t0 flags up\n\n\t",
  "Reconnecting...",
  "/bin ~ # sudo chown /system/",
  "$.system.on();\n\t[SYSTEM]:Antivirus Protocol Overridden\n\t[SERVER]:Firewall Disabled\n\t",
  "[ROOT]:Filesystem Formatted",
  "oauth: ks7bJpp8bvxz35hq",
  "**** Panel BlogHTML has fill-parent-flow for height, but isn't in a flowing down or up layout",
  "DispatchAsyncEvent backlog, failed to dispatch all this frame. 4871 of 4873 remaining",
  "*** Panel  has fill-parent-flow for height, but isn't in a flowing down or up layout",
  "Elapsed time: 0.00 seconds",
  "DispatchAsyncEvent backlog failed to dispatch all this frame 1520 of 5853 remaining",
  "Host_WriteConfiguration: Wrote hack_401.py",
  "DispatchAsyncEvent backlog, failed to dispatch all this frame. 1114 of 1643 remaining",
  "DispatchAsyncEvent backlog, failed to dispatch all this frame. 164 of 1153 remaining",
  "**** Panel BlogHTML has fill-parent-flow for height, but isn't in a flowing down or up layout",
  "Failed to communicate with routing cluster 'pwu'.",
  "Failed to communicate with routing cluster 'gtpe'.",
  "Communications with routing cluster 'pwu' restored.",
  "Ping measurement completed",
  " Ping location: bom = 38 + 3, maa = 52 + 5, dxb = 119 + 11 / 63 + 3, sgp = 85 + 8 / 85 + 5, man = 305 + 30 / 112 + 8, hkg = 268 + 26 / 114 + 5, par = 146 + 14, lux = 160 + 16 / 156 + 14, ams = 291 + 29 / 156 + 14, fra = 156 + 15, iad = 240 + 24 / 244 + 14,",
  "gru = 358 + 35",
  "RelayNetWorkStatus: avail = OK  config = OK  anyrelay = OK(OK)",
  "Host_WriteConfiguration: Wrote hack_401.py",
  "Host_WriteConfiguration: Wrote hack_41.py",
  "Host_WriteConfiguration: Wrote hack_41.py",
  "Refreshing ping measurements",
  "RelayNetWorkStatus: avail = OK  config = OK  anyrelay = OK(Refreshing ping measurements)",
  "Communications with routing cluster 'tsnm' have been disrupted.",
  "Communications with routing cluster 'pwu' have been disrupted.",
  "Communications with routing cluster 'pwu' restored.",
  "Communications with routing cluster 'tsnm' restored.",
  "Ping measurement has been active for 5.0s.Sending what we have to GC",
  "ams: 153ms via par(front = 143ms, back = 10ms)",
  "atl: 250ms via fra(front = 146ms, back = 104ms)",
  "  bom: 41ms via direct route",
  " can: 241ms via canm(front = 241ms, back = 0ms)",
  "canm: 241ms via direct route",
  "cant: 241ms via canm(front = 241ms, back = 0ms)",
  "  canu: 241ms via canm (front=241ms, back=0ms)",
  "dxb: 66ms via bom(front = 41ms, back = 25ms)",
  "eat: 263ms via maa(front = 50ms, back = 213ms)",
  "fra: 146ms via direct route",
  "gru: 352ms via direct route",
  " hkg: 112ms via maa(front = 50ms, back = 62ms)",
  "  iad: 237ms via fra (front=146ms, back=91ms)",
  "jnb: 319ms via par(front = 143ms, back = 176ms)",
  "lax: 266ms via maa(front = 50ms, back = 216ms)",
  "lhr: 159ms via par(front = 143ms, back = 16ms)",
  "lim: 361ms via maa(front = 50ms, back = 311ms)",
  "lux: 150ms via fra(front = 146ms, back = 4ms)",
  " maa: 50ms via direct route",
  "mad: 166ms via direct route",
  "man: 111ms via sgp(front = 84ms, back = 27ms)",
  "okc: 273ms via lhr(front = 168ms, back = 105ms)",
  "ord: 255ms via fra(front = 146ms, back = 109ms)",
  "par: 143ms via direct route",
  "pwg: 499ms via direct route",
  "pwj: 339ms via direct route",
  "pwu: 273ms via direct route",
  "pww: 432ms via direct route",
  "pwz: 441ms via direct route",
  "scl: 390ms via maa(front = 50ms, back = 340ms)",
  "sea: 249ms via tyo(front = 154ms, back = 95ms)",
  "sgp: 83ms via maa(front = 50ms, back = 33ms)",
  "  sha: 272ms via sham (front=272ms, back=0ms)",
  " sham: 272ms via direct route",
  "shat: 272ms via sham(front = 272ms, back = 0ms)",
  "shau: 272ms via sham(front = 272ms, back = 0ms)",
  "shb: 450ms via direct route",
  "sto: 162ms via sto2(front = 162ms, back = 0ms)",
  "  sto2: 162ms via direct route",
  "syd: 224ms via direct route",
  "tsn: 286ms via tsnm(front = 286ms, back = 0ms)",
  "tsnm: 286ms via direct route",
  "tsnt: 286ms via tsnm(front = 286ms, back = 0ms)",
  "tsnu: 286ms via tsnm(front = 286ms, back = 0ms)",
  "  tyo: 154ms via direct route",
  "tyo1: 154ms via tyo(front = 154ms, back = 0ms)",
  "vie: 158ms via fra(front = 146ms, back = 12ms)",
  "waw: 162ms via fra(front = 146ms, back = 16ms)",
  "Communications with routing cluster 'canu' have been disrupted.",
  "Communications with routing cluster 'canu' restored.",
  " Received Steam datagram ticket for server steamid: 90131014593736708 vport 0.",
  "Requesting session from maa#43 (155.133.232.98:27057).  Ping = 50+0=50 (front+back=total).",
  "Requesting session from bom#75 (155.133.233.99:27051).  Ping = 41+18=59 (front+back=total).",
  "Ping measurement completed",
  "Ping location: bom = 41 + 4, maa = 50 + 5, dxb = 114 + 11 / 66 + 4, sgp = 84 + 8 / 83 + 5, ",
  "man = 313 + 31 / 111 + 8, hkg = 272 + 27 / 112 + 5, par = 143 + 14, fra = 146 + 14,",
  " lux = 162 + 16 / 150 + 14, ams = 288 + 28 / 153 + 14, iad = 248 + 24 / 237 + 14, gru = 352 + 35",
  "RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)",
  " PNG load error Interlace handling should be turned on when using png_read_image",

  "SignalXWriteOpportunity(4)",
  "DispatchAsyncEvent backlog failed to dispatch all this frame  217 of 3092 remaining",
  "**** Panel  has fill-parent-flow for height, but isn't in a flowing down or up layout"
];

function runScript() {
  const rand = myArray[Math.floor(Math.random() * myArray.length)];
  const li = document.createElement("li");
  li.className = "green";
  li.appendChild(document.createTextNode(">" + rand));
  document.body.prepend(li);
}
